
INSERT INTO User (username, password, email, insolvent) VALUES ('sergio', 'sergio', 'sergio@sergio.com', 0);
INSERT INTO User (username, password, email, insolvent) VALUES ('ale', 'ale', 'sergio@sergio.com', 0);
INSERT INTO Service (id, name) VALUES (1);
INSERT INTO FixedPhone (id) VALUES (1);
INSERT INTO FixedPhone (id) VALUES (2);
DELETE FROM ServicePackage WHERE id=1 AND monthsNumber=12;
INSERT INTO ValidityPeriod (packageId, monthsNumber, monthlyFee) VALUES (1, 12, 12.5);
INSERT INTO ServicePackage (id, name) VALUES (1,"Basic");
DELETE FROM ServicePackage WHERE id=1;
INSERT INTO ServicePackage (id, name) VALUES (1,"Basic");
INSERT INTO ValidityPeriod (packageId, monthsNumber, monthlyFee) VALUES (1, 12, 12.5);
DELETE FROM ServicePackage WHERE id=1;
INSERT INTO ServicePackage (id, name) VALUES (1,"Basic");
INSERT INTO ValidityPeriod (packageId, monthsNumber, monthlyFee) VALUES (1, 11, 12.5);
DELETE FROM ServicePackage WHERE id=1;
INSERT INTO ServicePackage (id, name) VALUES (1,"Basic");
INSERT INTO ValidityPeriod (packageId, monthsNumber, monthlyFee) VALUES (1, 12, 12.5);
INSERT INTO ValidityPeriod (packageId, monthsNumber, monthlyFee) VALUES (1, 24, 12.5);
INSERT INTO ValidityPeriod (packageId, monthsNumber, monthlyFee) VALUES (1, 36, 12.5);
DELETE FROM ServicePackage WHERE id=1;
DELETE FROM ValidityPeriod WHERE packageId=1 AND monthsNumber=12;
DELETE FROM OptionalProduct WHERE id=1;
DELETE FROM OptionalProduct WHERE id=2;
DELETE FROM offersProducts WHERE packageId=1;
INSERT INTO ServicePackage (id, name) VALUES (1,"Basic");
INSERT INTO ValidityPeriod (packageId, monthsNumber, monthlyFee) VALUES (1, 12, 12.5);
INSERT INTO OptionalProduct (id, name, monthlyFee) VALUES (1, "SMS Addition", 10.0);
INSERT INTO OptionalProduct (id, name, monthlyFee) VALUES (2, "TV Addition", 15.0);
INSERT INTO offersProducts (packageId, productId) VALUES (1,1);
INSERT INTO offersProducts (packageId, productId) VALUES (1,2);
SELECT name FROM OptionalProduct WHERE id in ( SELECT productId from offersProducts WHERE packageId=1);
DELETE FROM User WHERE username='sergio';
DELETE FROM ServicePackage WHERE id=1;
DELETE FROM ValidityPeriod WHERE packageId=1 AND monthsNumber=12;
DELETE FROM OptionalProduct WHERE id=1;
DELETE FROM OptionalProduct WHERE id=2;
DELETE FROM offersProducts WHERE packageId=1;
DELETE FROM purchasesProducts WHERE customerOrderId=1;
DELETE FROM CustomerOrder WHERE id=1;
INSERT INTO User (username, password, email, insolvent) VALUES ('sergio', 'sergio', 'sergio@sergio.com', 0);
INSERT INTO ServicePackage (id, name) VALUES (1,"Basic");
INSERT INTO ValidityPeriod (packageId, monthsNumber, monthlyFee) VALUES (1, 12, 12.5);
INSERT INTO OptionalProduct (id, name, monthlyFee) VALUES (1, "SMS Addition", 10.0);
INSERT INTO OptionalProduct (id, name, monthlyFee) VALUES (2, "TV Addition", 15.0);
INSERT INTO offersProducts (packageId, productId) VALUES (1,1);
INSERT INTO offersProducts (packageId, productId) VALUES (1,2);
INSERT INTO CustomerOrder (id, date, hour, start, user, package , months, rejected, totalValue) VALUES (1, '2021-01-01', '13:00', '2021-03-01' ,"sergio", 1, 12, 0, 0);
INSERT INTO purchasesProducts (customerOrderId, productId) VALUES (1,1);
INSERT INTO purchasesProducts (customerOrderId, productId) VALUES (1,2);
SELECT totalValue FROM CustomerOrder WHERE id=1;
DELETE FROM User WHERE username='sergio';
INSERT INTO User (username, password, email, insolvent) VALUES ('sergio', 'sergio', 'sergio@sergio.com', 0);
INSERT INTO Auditing (username, email, lastRejectionAmount, lastRejectionDate, lastRejectionTime) VALUES ("sergio", "not@email.com", 0.7, 2021-01-01, 11:00:00);
